---
name: Number-Phone-Normalize
version: 0.220
author:
  - 'Claus FE<auml>rber <CFAERBER@cpan.org>'
abstract: Normalizes format of Phone Numbers.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  Number::Phone::Normalize:
    file: lib/Number/Phone/Normalize.pm
    version: 0.220
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
